[webservers]
192.168.1.7 ansible_user=ansible ansible_ssh_private_key_file=~/.ssh/id_rsa
[databases]
192.168.1.7 ansible_user=ansible ansible_ssh_private_key_file=~/.ssh/id_rsa

[all_servers:children]
webservers
databases
