---
- name: mySQL install karo
  apt: 
    name: "{{ db_package }}"
    state: present
    update_cache: yes

- name: mySQL start karo
  service: 
    name: "{{ db_service }}"
    state: started
    enabled: yes
